{
 "title": "EmBox6 SFP Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RxPower",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_rxpwr_p3" },
    { "expr": "sfp_rxpwr_p5" }
   ]
  },
  {
   "title": "Tx Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_txpwr_p3" },
    { "expr": "sfp_txpwr_p5" }
   ]
  },
  {
   "title": "VCC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_vcc_p3" },
    { "expr": "sfp_vcc_p5" }
   ]
  },
  {
   "title": "SFP Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_temperature_p3" },
    { "expr": "sfp_temperature_p5" }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  }
 ]
}