{
 "title": "Embox6 P3 P5 PTP Monitorv3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PTP Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "PTP Status History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "Packet Count Primary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pkt_cnt_304" },
    { "expr": "pkt_cnt_404" }
   ]
  },
  {
   "title": "Packet Count Secondary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pkt_cnt_305" },
    { "expr": "pkt_cnt_405" }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Seq Errors Primary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seq_err_304" },
    { "expr": "seq_err_404" }
   ]
  },
  {
   "title": "Seq Errors Secondary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seq_err_305" },
    { "expr": "seq_err_405" }
   ]
  },
  {
   "title": "RxPower",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_rxpwr_p3" },
    { "expr": "sfp_rxpwr_p5" }
   ]
  },
  {
   "title": "Tx Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_txpwr_p3" },
    { "expr": "sfp_txpwr_p5" }
   ]
  },
  {
   "title": "VCC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_vcc_p3" },
    { "expr": "sfp_vcc_p5" }
   ]
  },
  {
   "title": "SFP Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_temperature_p3" },
    { "expr": "sfp_temperature_p5" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Ping Latency (ms)",
   "type": "graph",
   "description": "Ping latency",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ping_latency" }
   ]
  },
  {
   "title": "API Read Time (Seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "api_read_time" }
   ]
  }
 ]
}