{
 "title": "Flows Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Packet Count Primary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pkt_cnt_104" },
    { "expr": "pkt_cnt_204" }
   ]
  },
  {
   "title": "Packet Count Secondary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pkt_cnt_105" },
    { "expr": "pkt_cnt_205" }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Seq Errors Primary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seq_err_104" },
    { "expr": "seq_err_204" }
   ]
  },
  {
   "title": "Seq Errors Secondary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seq_err_105" },
    { "expr": "seq_err_205" }
   ]
  }
 ]
}