{
 "title": "PTP Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PTP Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "PTP Status History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "PTP Offset From Master",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ptp_offset_from_master" }
   ]
  },
  {
   "title": "PTP Main Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ptp_mean_delay" },
    { "expr": "sfp_temperature_p5" }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {}
   ]
  }
 ]
}