{
 "title": "Embox6 P3 P5 PTP Monitorv3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PTP Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "PTP Status History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ptp_status" }
   ]
  },
  {
   "title": "Aggregated Primary Flows view",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch[0-9]_(VIDEO|AUDIO|ANCIL)_2110(_[0-9])?_prim_pkt_cnt\"}"
    }
   ]
  },
  {
   "title": "Aggregated Secondary Flows view",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch[0-9]_(VIDEO|AUDIO|ANCIL)_2110(_[0-9])?_sec_pkt_cnt\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 28, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregated Primary Flows Sequence Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Packets Errors" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch[0-9]_(VIDEO|AUDIO|ANCIL)_2110(_[0-9])?_prim_seq_err\"}"
    }
   ]
  },
  {
   "title": "Aggregated Secondary Flows Sequence Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Packets Errors" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch[0-9]_(VIDEO|AUDIO|ANCIL)_2110(_[0-9])?_sec_seq_err\"}"
    }
   ]
  },
  {
   "title": "RxPower",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_rxpwr_p3" },
    { "expr": "sfp_rxpwr_p5" }
   ]
  },
  {
   "title": "Tx Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_txpwr_p3" },
    { "expr": "sfp_txpwr_p5" }
   ]
  },
  {
   "title": "VCC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_vcc_p3" },
    { "expr": "sfp_vcc_p5" }
   ]
  },
  {
   "title": "SFP Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sfp_temperature_p3" },
    { "expr": "sfp_temperature_p5" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Ping Latency (ms)",
   "type": "graph",
   "description": "Ping latency",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ping_latency" }
   ]
  },
  {
   "title": "API Read Time (Seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "api_read_time" }
   ]
  }
 ]
}