{
 "title": "EmBox6 SFP Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RxPower",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"sfp_rxpwr_p[0-9]\"}"
    }
   ]
  },
  {
   "title": "Tx Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"sfp_txpwr_p[0-9]\"}"
    }
   ]
  },
  {
   "title": "VCC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"sfp_vcc_p[0-9]\"}"
    }
   ]
  },
  {
   "title": "SFP Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"sfp_temperature_p[0-9]\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  }
 ]
}