{
 "title": "FlowsMonitor",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ChannelNumber", "query": "1,2,3,4,5,6,7,8,9" },
   { "name": "DataType", "query": "AUDIO,VIDEO,ANCIL" }
  ]
 },
 "panels": [
  {
   "title": "Primary Packet Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch${ChannelNumber}_${DataType}_2110_prim_pkt_cnt\"}"
    }
   ]
  },
  {
   "title": "Primary Sequence Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch${ChannelNumber}_${DataType}_2110_prim_seq_err\"}"
    }
   ]
  },
  {
   "title": "Secondary Packet Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch${ChannelNumber}_${DataType}_2110_prim_pkt_cnt\"}"
    }
   ]
  },
  {
   "title": "Secondary Sequence Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ch${ChannelNumber}_${DataType}_2110_sec_seq_err\"}"
    }
   ]
  }
 ]
}